# Generated by Django 4.2.7 on 2023-11-20 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='therapist_id',
            field=models.UUIDField(default=uuid.UUID('713e5588-a442-4491-a4f2-17c5caec6b05'), editable=False, unique=True),
        ),
    ]
