# Generated by Django 4.2.7 on 2023-11-20 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_remove_therapist_therapist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='therapist_id',
            field=models.UUIDField(default=uuid.UUID('136985e1-76be-49c6-b63e-0c1da2278ea7'), editable=False, unique=True),
        ),
    ]
