# Generated by Django 4.2.7 on 2023-11-21 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_therapist_therapist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='therapist_id',
            field=models.UUIDField(default=uuid.UUID('889dc5ca-de5e-41ee-a2f0-796a41d59e84'), editable=False, unique=True),
        ),
    ]
