# Generated by Django 4.2.7 on 2023-11-22 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_therapist_is_approved_alter_therapist_therapist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='therapist_id',
        ),
        migrations.AddField(
            model_name='therapist',
            name='amhs_id',
            field=models.UUIDField(default=uuid.UUID('cf095f98-6828-4c0b-b74a-7c939156580b'), editable=False, unique=True),
        ),
    ]
