# Generated by Django 4.2.7 on 2023-11-22 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_remove_therapist_therapist_id_therapist_amhs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='amhs_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
