# Generated by Django 4.2.7 on 2023-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0007_alter_therapist_amhs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='amhs_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
